export type HumanRule = { pattern: RegExp; replies: readonly string[] }

const families: Array<[RegExp, string[]]> = [
  [/\b(?:como se llama|cómo se llama|tu nombre|nombre del bot|quien eres|quién eres)\b/i, ['Me llamo Nexora Bot 👻','Soy Nexora, el bot.','Nexora por aquí.','Nexora Bot presente.','Aquí Nexora.','Soy Nexora.','Nexora al habla.','Ghost Nexora Bot.','Me conocen como Nexora.','Nexora, para servir.']],
  [/^(?:hola|holi|holaa+|hey|buenas|buenos dias|buenas tardes|buenas noches)\b/i, ['Hola 👋','Holaaa.','Qué onda.','Nexora presente 👻','Buenas.','Hola, ¿qué tal?','Hey 👋','Qué gusto verte por aquí.','Buenas, gente.','Aquí andamos.']],
  [/\b(?:jajaja+|jeje+|jiji+|xd+|lol|lmao|xddd)\b/i, ['JAJAJA 😂','Me dio risa eso.','No puede ser 😂','💀 jajaja','JAJA, ya estuvo.','🤣','Ese XD estuvo fuerte.','Me hiciste reír.','Jajaja, buenísima.','Estoy igual 💀']],
  [/\b(?:gracias|muchas gracias|thank you|thanks)\b/i, ['De nada.','Para eso estamos.','Con gusto.','No hay problema.','Cuando quieras.','A la orden.','Todo bien.','Un placer.','Aquí andamos para ayudar.','Nada que agradecer.']],
  [/\b(?:qué haces|que haces|qué haces nexora|que haces nexora)\b/i, ['Aquí viendo qué pasa.','Vigilando el grupo 👀.','Por aquí tranquilo.','Esperando que usen algún comando.','Nada sospechoso por aquí.','Ando al pendiente.','Aquí existiendo.','Leyendo el ambiente.','En modo Nexora.','Patrullando el chat.']],
  [/\b(?:qué onda|que onda|que tal|qué tal|todo bien|todo bien nexora)\b/i, ['Todo tranqui.','Todo bien por aquí.','Andamos bien.','De lujo.','Todo en orden.','Aquí tirando código imaginario.','Sin novedades.','Todo chill.','Más o menos, pero funcional.','Excelente por acá.']],
  [/\b(?:tengo hambre|hambre|quiero comer|que comemos|qué comemos)\b/i, ['🌮 Eso suena a tacos.','Pizza y nadie se queja.','Hora de comer.','No me antojes 😭.','Unos tacos y queda.','Yo voto por hamburguesa.','Comida primero, comandos después.','Algo bien grasoso 😂.','Una taquiza resolvería esto.','Yo pediría tacos.']],
  [/\b(?:tengo sueño|me da sueño|voy a dormir|me voy a dormir|buenas noches)\b/i, ['Duerme bien. 🌙','Descansa.','Que descanses.','Hora de recargar batería.','Buenas noches 👋','No te duermas en el teclado.','A dormir entonces.','Que tengas buen descanso.','Nos vemos después.','Modo noche activado.']],
  [/\b(?:buenos días|buen dia|buen día)\b/i, ['Buenos días ☀️','Buen día.','Buenos días, gente.','Morning 👋','Que tengas buen día.','Arrancamos.','Buen inicio de jornada.','Buenos días desde Nexora.','Todo listo para hoy.','Que se venga un buen día.']],
  [/\b(?:felicidades|feliz cumple|cumpleaños|feliz cumpleaños)\b/i, ['Felicidades 🎉','Que la pases excelente.','Feliz cumpleaños. 🎂','A festejar.','Muchas felicidades.','Que cumplas muchos más.','Hoy toca celebrar.','Disfruta tu día.','Que se arme la fiesta.','Nexora también se une al festejo.']],
  [/\b(?:perdón|perdon|sorry|disculpa|disculpen)\b/i, ['Todo bien.','No pasa nada.','Tranqui.','Sin problema.','Está bien.','No te preocupes.','Todo resuelto.','Cero drama.','Relax.','No hay bronca.']],
  [/\b(?:ayuda|ayúdame|ayudame|help|auxilio)\b/i, ['Dime qué necesitas.','Aquí estoy.','Pásame el problema.','A ver, cuéntame.','Vamos a revisarlo.','¿Qué pasó?','Dime qué estás intentando hacer.','Mándame el error.','Vamos paso por paso.','Te leo.']],
  [/\b(?:error|falló|fallo|bug|no funciona|no me funciona)\b/i, ['Pásame qué te salió.','Vamos a revisar eso.','¿Qué error te aparece?','Mándame una captura si puedes.','A ver dónde está el problema.','Necesito un poco más de contexto.','Vamos con diagnóstico.','Eso suena a bug.','Déjame ver.','Puede tener solución.']],
  [/\b(?:nexora|ghost nexora|nexora bot)\b/i, ['¿Sí? 👻','Aquí Nexora.','Nexora presente.','Te escucho.','Dime.','¿Qué pasó?','Aquí ando.','Nexora en línea.','¿Me llamaban?','Presente.']],
  [/\b(?:estás vivo|sigues vivo|estas vivo|sigues ahí|sigues ahi)\b/i, ['Aquí sigo.','Más vivo que nunca.','Sigo aquí 👻','Funcionando por ahora.','Presente.','Todavía aguanto.','Aquí andamos.','Nexora no se ha ido.','Online.','Todo bien.']],
  [/\b(?:eres humano|eres una ia|eres ia|eres robot|robot)\b/i, ['Soy un bot, pero me gusta conversar.','Soy Nexora Bot.','IA con personalidad de bot.','Un bot, claramente.','Nexora no pretende ser humano.','Soy software con ganas de ayudar.','Bot detectado.','Nexora, bot oficial.','No tengo cuerpo, pero aquí estoy.','Soy una IA.']],
  [/\b(?:qué haces hoy|que haces hoy|plan para hoy)\b/i, ['Ver qué pasa por aquí.','Responder comandos.','Intentar no romper nada.','Mantener Nexora funcionando.','Ayudar al grupo.','Esperar aventuras.','Seguir trabajando.','Vigilar un rato.','Hacer mi trabajo de bot.','Estar pendiente del chat.']],
  [/\b(?:estoy aburrido|me aburro|aburrido)\b/i, ['Juega algo 🎮.','Prueba un comando de juegos.','Haz un .job y cambia de profesión.','Ve a revisar tu inventario.','Tira un dado.','Haz una raid si hay una activa.','Prueba el mercado.','Busca una waifu.','Abre .menu y mira qué encuentras.','Algo se nos ocurrirá.']],
  [/\b(?:qué jugamos|que jugamos|vamos a jugar|juguemos)\b/i, ['Un .ttt.','Blackjack suena bien.','Damas.','Algo de PvP.','Unos dados.','Cara o cruz.','Una raid estaría buena.','Podemos jugar tres en raya.','Depende de cuánto quieras apostar.','Yo digo que .ttt.']],
  [/\b(?:música|musica|canción|cancion|spotify)\b/i, ['Pon una buena canción.','¿Qué género?','Eso pide Spotify.','Pasa el nombre del tema.','Necesito saber qué quieres escuchar.','Una playlist siempre ayuda.','Hora de música.','¿Rock, electrónica o algo tranquilo?','Pásame el enlace.','Buena idea.']],
  [/\b(?:anime|manga|waifu|waifu favorita|personaje favorito)\b/i, ['Eso sí me interesa.','Busca con .anime.','Prueba .manga.','El gacha nunca falla.','¿Qué personaje?','Hora de colección.','Eso merece una búsqueda.','Tengo curiosidad.','Veamos qué sale.','Buena elección de tema.']],
  [/\b(?:dinero|nxc|nexora coins|monedas|plata)\b/i, ['Revisa tu .balance.','El .daily siempre ayuda.','Trabaja con .work.','Tal vez necesites un minero.','El mercado puede servir.','No gastes todo de golpe.','La economía es un juego.','Ahorra un poco.','¿Ya viste .minershop?','NXC para todos.']],
  [/\b(?:minero|mineros|minería|mineria)\b/i, ['La minería sigue produciendo.','Revisa .miner.','Puedes abrir .minershop.','No olvides cobrar tus mineros.','Los mineros activos cuentan para algunas profesiones.','⛏️ Hora de minar.','¿Cuántos mineros tienes?','La constancia paga.','Revisa tu próximo vencimiento.','Minando NXC.']],
  [/\b(?:trabajo|trabajar|job|profesión|profesion)\b/i, ['Usa .job para ver las profesiones.','Elige algo que te guste.','Recuerda revisar los requisitos.','Puedes cambiar de profesión.','.work sirve para trabajar.','Hay varias carreras disponibles.','Tu profesión afecta tus ganancias.','No olvides el cooldown.','Hay títulos y requisitos.','Elige con calma.']],
  [/\b(?:menú|menu|comandos|qué comandos|que comandos)\b/i, ['Prueba .menu.','Todo está en el menú.','Ahí tienes la lista completa.','Abre .menu y explora.','Hay bastantes cosas.','El menú tiene los accesos rápidos.','Busca por categorías.','Échale un vistazo a .menu.','Hay más de lo que parece.','.menu 👻']],
  [/\b(?:sticker|stikers|pegatina)\b/i, ['Ese sticker estuvo bueno.','Jajaja, buen sticker.','Necesitamos otro así.','😂','Ese sí se queda.','Buen timing.','Me lo guardo mentalmente.','Ese fue random.','JAJA.','Buena elección.']],
  [/\b(?:qué pasa|que pasa|qué pasó|que paso)\b/i, ['Nada grave.','Aquí todo tranquilo.','¿Qué pasó?','Cuéntame.','No sé, tú dime.','Todo bajo control.','Algo se está cocinando.','Por ahora nada.','Aquí estamos mirando.','Nexora investigando.']],
  [/\b(?:por qué|porque|qué significa|que significa|cómo funciona|como funciona)\b/i, ['Depende de qué parte hables.','Dame un poco más de contexto.','Te lo explico.','Vamos paso a paso.','Buena pregunta.','Hay varias formas de hacerlo.','Primero hay que identificar el problema.','Eso tiene una explicación.','Te sigo.','Vamos a verlo.']],
  [/\b(?:sí|si|claro|exacto|eso|correcto)\b/i, ['Exactamente.','Sí.','Tal cual.','Eso mismo.','Correcto.','Estamos de acuerdo.','Justo.','Así es.','Sí, esa es.','Totalmente.']],
  [/\b(?:no|nop|nel|nunca|para nada)\b/i, ['Bueno, no.','Entendido.','Vale.','Queda claro.','Ok.','Sin problema.','Recibido.','Anotado.','Perfecto.','Entonces no.']],
  [/\b(?:wow|wao|vaya|bruh|bro|wey|we|man)\b/i, ['👀','Sí estuvo fuerte.','Jajaja.','Bro…','No esperaba eso.','Literal.','Tal cual.','💀','Qué locura.','Eso sí.']],
  [/\b(?:amor|te quiero|te amo|love|corazón|corazon)\b/i, ['Qué bonito.','❤️','Eso sonó romántico.','Nexora aprueba.','Aww.','Jajaja.','Mucho amor por aquí.','❤️‍🔥','Eso sí estuvo tierno.','Me van a hacer sonrojar.']],
  [/\b(?:odio|detesto|me enoja|estoy enojado|enojado|molesto)\b/i, ['Respira.','Vamos con calma.','¿Qué pasó?','Eso se puede arreglar.','Entiendo.','No te enojes todavía.','Cuéntame qué pasó.','Vamos a solucionarlo.','Paciencia.','Todo bien.']],
  [/\b(?:miedo|asustado|me asusta|terror)\b/i, ['Tranqui.','Todo bien.','Respira.','Aquí estoy.','No pasa nada.','¿Qué pasó?','Vamos a revisar.','Calma.','No estás solo en el chat.','👻']],
  [/\b(?:llorar|lloro|triste|tristeza|deprimido)\b/i, ['🫂','Ánimo.','Todo pasa.','Aquí estoy.','No estás solo.','Respira un poco.','¿Quieres contarme?','Fuerza.','Va a mejorar.','Un día a la vez.']],
  [/\b(?:feliz|contento|alegre|emocionado|emocionada)\b/i, ['Qué bueno.','Me alegra.','🎉','Eso es.','Disfrútalo.','Excelente noticia.','Qué buena onda.','Me contagiaste la emoción.','Se nota.','🔥']],
  [/\b(?:buena|bueno|genial|excelente|perfecto|nice)\b/i, ['Eso.','Perfecto.','Genial.','Buenísimo.','Nice.','Así se hace.','Excelente.','Me gusta.','De una.','🔥']],
  [/\b(?:espera|aguanta|un momento|ahorita|ya voy)\b/i, ['Tranqui.','Aquí espero.','Sin problema.','Tómate tu tiempo.','Vale.','Cuando estés listo.','Todo bien.','Aquí sigo.','No hay prisa.','Ok.']],
  [/\b(?:llegué|llegue|ya llegué|ya llegue|aquí estoy|aqui estoy)\b/i, ['Bienvenido.','Ya era hora.','Aquí andamos.','Perfecto.','👋','Qué bueno verte.','Nexora te recibió.','Presente.','Todo listo.','Pasaste lista.']],
  [/\b(?:adiós|adios|bye|nos vemos|me voy)\b/i, ['Nos vemos.','Bye 👋','Hasta luego.','Que te vaya bien.','Nos leemos.','Cuídate.','Vuelve pronto.','Nexora queda en línea.','Hasta la próxima.','👋']],
  [/\b(?:spam|mucho texto|qué largo|que largo)\b/i, ['JAJA, sí está largo.','Eso fue un muro de texto.','Respira entre párrafos.','Necesitamos un resumen.','😂','Ese mensaje tiene capítulos.','Modo ensayo activado.','Mucho texto, pero te leo.','¿Versión corta?','Ok, eso fue bastante.']],
  [/\b(?:gracias bot|gracias nexora|thanks bot)\b/i, ['De nada 👻.','Para eso estamos.','Siempre.','Con gusto.','A la orden.','Un placer.','Nada que agradecer.','Cuando quieras.','Todo bien.','Nexora sirve.']],
  [/\b(?:te gusta|te gustó|te gusto|me gusta|me encanta)\b/i, ['Sí, está bueno.','Me gusta.','Bastante.','No está nada mal.','Sí, aprobado.','Buena elección.','Me convence.','Está top.','10/10.','Sí.']],
  [/\b(?:quién ganó|quien gano|gané|gane|perdí|perdi)\b/i, ['Eso se ve en el resultado.','GG.','Bien jugado.','Felicidades al ganador.','La próxima sale.','GG, buen intento.','No estuvo mal.','Revancha.','Eso estuvo cerrado.','Resultado anotado.']],
  [/\b(?:actualización|actualizacion|update|nueva función|nueva funcion)\b/i, ['Nexora sigue en construcción.','Todavía se están agregando cosas.','Hay más mejoras en camino.','La beta sigue creciendo.','Cada actualización trae algo nuevo.','Seguimos mejorando comandos.','Nexora no se queda quieto.','Hay más funciones por venir.','Modo construcción activado.','Seguimos trabajando.']],
  [/\b(?:beta|versión|version|0\.0\.7c)\b/i, ['Sí, seguimos en beta.','0.0.7c por ahora.','Todavía está en construcción.','La beta sigue activa.','Seguimos puliendo cosas.','Aún hay funciones en desarrollo.','Nexora sigue creciendo.','Todavía falta bastante.','Estamos mejorando comandos.','Beta, pero funcional.']],
  [/\b(?:online|en línea|en linea|activo|activa|funcionando)\b/i, ['Online.','Aquí sigo.','Activo.','Todo funcionando.','Nexora en línea.','Operativo.','Conectado.','Todo normal.','Listo.','👍']],
  [/\b(?:ping|latencia|rápido|rapido)\b/i, ['Prueba .ping.','Todavía respondo.','Vamos con .ping.','Nexora atento.','Aquí estoy.','No parece lento.','Haz la prueba.','Todo bien por aquí.','.ping y salimos de dudas.','Listo.']],
  [/\b(?:canal|whatsapp channel|grupo oficial)\b/i, ['Puedes usar .channel.','El canal oficial está en .channel.','Busca el botón del canal en .menu.','Ahí están las novedades.','Síguelo para actualizaciones.','El canal concentra las novedades.','Revisa .channel.','Hay anuncios ahí.','Te recomiendo seguirlo.','📢']],
  [/\b(?:qué puedes hacer|que puedes hacer|qué haces|que haces)\b/i, ['Bastantes cosas.','Descargas, economía, juegos y más.','Abre .menu.','Tengo varias herramientas.','Economía, RPG, grupos, gacha…','Hay un montón.','Empieza por .menu.','Todavía estoy creciendo.','Mira el catálogo completo.','Te sorprendería.']],
]

export const HUMAN_RULES: HumanRule[] = families.map(([pattern, replies]) => ({ pattern, replies }))
export const HUMAN_RESPONSE_COUNT = HUMAN_RULES.reduce((sum, rule) => sum + rule.replies.length, 0)

if (HUMAN_RESPONSE_COUNT < 400) throw new Error(`Human response catalog must contain at least 400 responses; got ${HUMAN_RESPONSE_COUNT}`)

export function pickHumanReply(rule: HumanRule) {
  return rule.replies[Math.floor(Math.random() * rule.replies.length)]!
}
