import fs from 'node:fs'
import path from 'node:path'

type Matrix = Float32Array[]
export function zeros(rows: number, cols: number): Matrix { return Array.from({ length: rows }, () => new Float32Array(cols)) }
export function randomMatrix(rows: number, cols: number, scale = 0.02, seed = Math.random()): Matrix {
  const m = zeros(rows, cols); let state = (Math.floor(seed * 0xffffffff) >>> 0) || 1
  for (let i = 0; i < rows; i++) for (let j = 0; j < cols; j++) { state = (state * 1664525 + 1013904223) >>> 0; m[i]![j] = (state / 0x100000000 - 0.5) * scale }
  return m
}
function softmax(row: Float32Array) { let max = -Infinity; for (const v of row) if (v > max) max = v; const out = new Float32Array(row.length); let sum = 0; for (let i = 0; i < row.length; i++) { out[i] = Math.exp(Math.max(-30, row[i]! - max)); sum += out[i]! } for (let i = 0; i < out.length; i++) out[i] /= Math.max(sum, 1e-9); return out }
function layerNorm(x: Float32Array, eps = 1e-5) { let mean = 0; for (const v of x) mean += v; mean /= x.length; let variance = 0; for (const v of x) variance += (v - mean) ** 2; variance /= x.length; const out = new Float32Array(x.length); const inv = 1 / Math.sqrt(variance + eps); for (let i = 0; i < x.length; i++) out[i] = (x[i]! - mean) * inv; return out }
function clone(m: Matrix) { return m.map((r) => new Float32Array(r)) }
function matmul(a: Matrix, b: Matrix) { const out = zeros(a.length, b[0]?.length ?? 0); for (let i = 0; i < a.length; i++) for (let k = 0; k < b.length; k++) { const v = a[i]![k]!; if (!v) continue; for (let j = 0; j < out[i]!.length; j++) out[i]![j] += v * b[k]![j]! } return out }
function pos(p: number, i: number, dim: number) { const angle = p / Math.pow(10000, (2 * Math.floor(i / 2)) / dim); return i % 2 === 0 ? Math.sin(angle) : Math.cos(angle) }

export class MiniTransformer {
  vocabSize: number; dim = 128; layers = 4; heads = 4; headDim = 32; lr = 0.001; momentum = 0.9
  embedding: Matrix; Wq: Matrix[] = []; Wk: Matrix[] = []; Wv: Matrix[] = []; Wo: Matrix[] = []; Wff1: Matrix[] = []; Wff2: Matrix[] = []; Wout: Matrix
  vEmbedding: Matrix; vWq: Matrix[] = []; vWk: Matrix[] = []; vWv: Matrix[] = []; vWo: Matrix[] = []; vWff1: Matrix[] = []; vWff2: Matrix[] = []; vWout: Matrix

  constructor(vocabSize: number) {
    this.vocabSize = Math.max(4, vocabSize); this.embedding = randomMatrix(this.vocabSize, this.dim); this.Wout = randomMatrix(this.dim, this.vocabSize); this.vEmbedding = zeros(this.vocabSize, this.dim); this.vWout = zeros(this.dim, this.vocabSize)
    for (let l = 0; l < this.layers; l++) { this.Wq.push(randomMatrix(this.dim, this.dim)); this.Wk.push(randomMatrix(this.dim, this.dim)); this.Wv.push(randomMatrix(this.dim, this.dim)); this.Wo.push(randomMatrix(this.dim, this.dim)); this.Wff1.push(randomMatrix(this.dim, this.dim * 4)); this.Wff2.push(randomMatrix(this.dim * 4, this.dim)); this.vWq.push(zeros(this.dim, this.dim)); this.vWk.push(zeros(this.dim, this.dim)); this.vWv.push(zeros(this.dim, this.dim)); this.vWo.push(zeros(this.dim, this.dim)); this.vWff1.push(zeros(this.dim, this.dim * 4)); this.vWff2.push(zeros(this.dim * 4, this.dim)) }
  }
  private update(p: number, v: number, g: number) { const nv = this.momentum * v + this.lr * g; return { value: p - nv, velocity: nv } }
  forward(tokens: number[]) {
    const ids = tokens.filter((t) => t >= 0 && t < this.vocabSize).slice(-64); let x: Matrix = ids.map((t, p) => { const r = new Float32Array(this.embedding[t] ?? this.dim); for (let i = 0; i < this.dim; i++) r[i] += pos(p, i, this.dim); return r }); const inputs = clone(x); const caches: Array<{ norm1: Matrix; attended: Matrix; ff1: Matrix; ff2: Matrix; output: Matrix }> = []
    for (let l = 0; l < this.layers; l++) { const Q = matmul(x, this.Wq[l]!); const K = matmul(x, this.Wk[l]!); const V = matmul(x, this.Wv[l]!); const attended = zeros(x.length, this.dim); for (let i = 0; i < x.length; i++) { const scores = new Float32Array(i + 1); for (let j = 0; j <= i; j++) { let dot = 0; for (let h = 0; h < this.heads; h++) { const start = h * this.headDim; for (let d = 0; d < this.headDim; d++) dot += Q[i]![start + d]! * K[j]![start + d]! } scores[j] = dot / Math.sqrt(this.headDim) } const a = softmax(scores); for (let j = 0; j <= i; j++) for (let d = 0; d < this.dim; d++) attended[i]![d] += a[j]! * V[j]![d]! }
      const projected = matmul(attended, this.Wo[l]!); const norm1 = projected.map((r, i) => { const z = new Float32Array(this.dim); for (let d = 0; d < this.dim; d++) z[d] = x[i]![d]! + r[d]!; return layerNorm(z) }); const ff1 = matmul(norm1, this.Wff1[l]!); for (const r of ff1) for (let i = 0; i < r.length; i++) if (r[i]! < 0) r[i] = 0; const ff2 = matmul(ff1, this.Wff2[l]!); x = ff2.map((r, i) => { const z = new Float32Array(this.dim); for (let d = 0; d < this.dim; d++) z[d] = norm1[i]![d]! + r[d]!; return layerNorm(z) }); caches.push({ norm1: clone(norm1), attended: clone(attended), ff1: clone(ff1), ff2: clone(ff2), output: clone(x) }) }
    const last = x.at(-1) ?? new Float32Array(this.dim); const logits = new Float32Array(this.vocabSize); for (let v = 0; v < this.vocabSize; v++) { let score = 0; for (let d = 0; d < this.dim; d++) score += last[d]! * this.Wout[d]![v]!; logits[v] = score }
    return { logits, cache: { tokens: ids, inputs, layers: caches, finalX: x } }
  }
  trainStep(tokens: number[], targetId: number) { const target = Math.max(0, Math.min(this.vocabSize - 1, targetId)); const { logits, cache } = this.forward(tokens); const probs = softmax(logits); const loss = -Math.log(Math.max(probs[target]!, 1e-9)); const d = new Float32Array(probs); d[target] -= 1; const last = cache.finalX.at(-1) ?? new Float32Array(this.dim); const dLast = new Float32Array(this.dim); for (let j = 0; j < this.dim; j++) { let g = 0; for (let v = 0; v < this.vocabSize; v++) { g += d[v]! * this.Wout[j]![v]!; const n = this.update(this.Wout[j]![v]!, this.vWout[j]![v]!, last[j]! * d[v]!); this.Wout[j]![v] = n.value; this.vWout[j]![v] = n.velocity } dLast[j] = g }
    for (let l = this.layers - 1; l >= 0; l--) { const c = cache.layers[l]!; for (let i = 0; i < c.ff2.length; i++) for (let j = 0; j < this.dim; j++) { const g = dLast[j]! / Math.max(1, c.ff2.length); for (let k = 0; k < this.dim * 4; k++) { const n = this.update(this.Wff2[l]![k]![j]!, this.vWff2[l]![k]![j]!, c.ff1[i]![k]! * g); this.Wff2[l]![k]![j] = n.value; this.vWff2[l]![k]![j] = n.velocity } } for (let i = 0; i < c.attended.length; i++) for (let j = 0; j < this.dim; j++) { const g = dLast[j]! / Math.max(1, c.attended.length); for (let k = 0; k < this.dim; k++) { const n = this.update(this.Wo[l]![k]![j]!, this.vWo[l]![k]![j]!, c.attended[i]![k]! * g); this.Wo[l]![k]![j] = n.value; this.vWo[l]![k]![j] = n.velocity } } }
    for (const t of cache.tokens) if (t >= 0 && t < this.vocabSize) for (let j = 0; j < this.dim; j++) { const n = this.update(this.embedding[t]![j]!, this.vEmbedding[t]![j]!, dLast[j]! * 0.1); this.embedding[t]![j] = n.value; this.vEmbedding[t]![j] = n.velocity }
    return loss }
  sample(logits: Float32Array, temperature = 0.8, topK = 32) { const candidates = Array.from(logits, (value, index) => ({ value: Math.exp(value / Math.max(temperature, 0.1)), index })).sort((a, b) => b.value - a.value).slice(0, Math.min(topK, logits.length)); const total = candidates.reduce((s, x) => s + x.value, 0); let r = Math.random() * Math.max(total, 1e-9); for (const c of candidates) { r -= c.value; if (r <= 0) return c.index } return candidates[0]?.index ?? 0 }
  save(filePath = './data/model.bin') { fs.mkdirSync(path.dirname(filePath), { recursive: true }); const meta = Buffer.from(JSON.stringify({ version: 3, vocabSize: this.vocabSize, dim: this.dim, layers: this.layers, heads: this.heads }) + '\n'); const matrices: Matrix[] = [this.embedding, ...this.Wq, ...this.Wk, ...this.Wv, ...this.Wo, ...this.Wff1, ...this.Wff2, this.Wout]; const payload = matrices.flatMap((m) => m.map((r) => Buffer.from(r.buffer, r.byteOffset, r.byteLength))); fs.writeFileSync(filePath, Buffer.concat([meta, ...payload])) }
  load(filePath = './data/model.bin') { if (!fs.existsSync(filePath)) return false; const buffer = fs.readFileSync(filePath); const split = buffer.indexOf(10); if (split < 0) return false; try { const meta = JSON.parse(buffer.subarray(0, split).toString('utf8')) as Record<string, number>; if (meta.version !== 3 || meta.vocabSize !== this.vocabSize || meta.dim !== this.dim || meta.layers !== this.layers || meta.heads !== this.heads) return false; let offset = split + 1; const read = (rows: number, cols: number) => { const m = zeros(rows, cols); for (let i = 0; i < rows; i++) for (let j = 0; j < cols; j++) { m[i]![j] = buffer.readFloatLE(offset); offset += 4 } return m }; this.embedding = read(this.vocabSize, this.dim); this.Wq = Array.from({ length: this.layers }, () => read(this.dim, this.dim)); this.Wk = Array.from({ length: this.layers }, () => read(this.dim, this.dim)); this.Wv = Array.from({ length: this.layers }, () => read(this.dim, this.dim)); this.Wo = Array.from({ length: this.layers }, () => read(this.dim, this.dim)); this.Wff1 = Array.from({ length: this.layers }, () => read(this.dim, this.dim * 4)); this.Wff2 = Array.from({ length: this.layers }, () => read(this.dim * 4, this.dim)); this.Wout = read(this.dim, this.vocabSize); return true } catch { return false } }
}
